FROM amazoncorretto:11
VOLUME /tmp
ARG APP_DEPENDENCY_DIR
ARG APP_CLASS=com.ieee2030.scheduling.scheduler.SchedulerApplication
ENV SPRINGBOOT_APPLICATION_CLASS=${APP_CLASS}
COPY ${APP_DEPENDENCY_DIR}/BOOT-INF/lib /app/lib
COPY ${APP_DEPENDENCY_DIR}/META-INF /app/META-INF
COPY ${APP_DEPENDENCY_DIR}/BOOT-INF/classes /app
EXPOSE 8080
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -cp app:app/lib/* ${SPRINGBOOT_APPLICATION_CLASS}"]
