CREATE USER user1 WITH
    LOGIN
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION
    PASSWORD 'password1';

CREATE DATABASE ieeedb
    WITH
    OWNER = user1
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

GRANT TEMPORARY, CONNECT ON DATABASE ieeedb TO PUBLIC;
GRANT ALL ON DATABASE ieeedb TO user1;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to user1;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public to user1;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public to user1;
